version: '3.3'
services:

  db:
    container_name: ${DOCKER_PROJECT_NAME}-db
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
    ports:
      - ${DOCKER_DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}

  nginx:
    container_name: ${DOCKER_PROJECT_NAME}-nginx
    image: nginx:alpine
    ports:
      - ${DOCKER_APP_PORT}:80
    volumes:
      - ${DOCKER_COMPOSER_CACHE}:/root/.composer/cache
      - ./:/var/www/symfony4
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    container_name: ${DOCKER_PROJECT_NAME}-php
    build: docker/php
    volumes:
      - ./:/var/www/symfony4

volumes:
  db: